set nocompatible
set history=1000
set hidden
set shell=/usr/bin/env\ bash                                                " load .bashrc when starting shell from Vim
set tabstop=2
set shiftwidth=2
set softtabstop=2
set expandtab
set noswapfile
set ignorecase
set smartcase
set incsearch
set number
set ls=2
noremap gc :!rst2html.py --stylesheet-dirs=~/.config/docutils/css/ --stylesheet-path=base.css,f.css % %:r.html <cr><cr>
noremap gp :w <cr> :!python % <cr>
command Jade :!jade %
command Mocha :!mocha --ui tdd
command Py :!python % -o 
command Browserify :!Browserify % -o %:p:h/bundle.js
" Pim things
let g:pim_kerberos_bin_dir = '/opt/likewise/bin/'
let g:pim_pig_command = '/export/apps/pig/latest/bin/pig'

augroup extra
  autocmd!
  autocmd BufRead,BufNewFile *.pig set filetype=pig
  autocmd BufRead,BufNewFile *.jade set filetype=jade
augroup END

" source extra vimrc if it exists
let s:extra_vimrc = $HOME . '/.extra/vimrc'
if filereadable(s:extra_vimrc)
  execute 'source ' . s:extra_vimrc
endif

filetype plugin on                                                          " reenable per filetype loading
syntax enable                                                               " activate syntax highlighting

let s:loaded_plugins = 1
